# Generated by Django 4.0.3 on 2022-07-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=30)),
                ('date_of_registration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
