# Generated by Django 4.0.3 on 2022-07-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('old_price', models.CharField(max_length=20, verbose_name='Старая цена')),
                ('new_price', models.CharField(max_length=20, verbose_name='Новая цена')),
                ('percent_of_sale', models.CharField(max_length=10, verbose_name='Скидка')),
                ('date_of_end', models.CharField(max_length=10, verbose_name='Окончание')),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_registration',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=30, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
